// apps/web/src/pages/auth/login.tsx
import { useForm } from "react-hook-form"
import { z } from "zod"
import { zodResolver } from "@hookform/resolvers/zod"
import Input from "../../components/Input"
import Button from "../../components/Button"
import { useMutation } from "@tanstack/react-query"
import client from "../../httpClient"
import { Link, useNavigate } from "react-router-dom"
import { toast } from "react-hot-toast"
import { md5 } from "hash-wasm"
import useStore from "../../store"

const schema = z.object({
  emailOrUsername: z.string()
    .min(1, "Required field"),
  password: z.string()
    .min(1, "Required field")
})
type FormValues = z.infer<typeof schema>

const LoginPage: React.FC = () => {
  const setUser = useStore(state => state.setUser)
  const navigate = useNavigate()

  const { mutateAsync: login } = useMutation({
    mutationFn: async ({ emailOrUsername, password }: FormValues) => {
      const { error, data } = await client.api.auth.login.post({
        emailOrUsername: emailOrUsername,
        password: await md5(password)
      })

      if (error) {
        throw new Error(error.value as string)
      }

      return data
    },
    onSuccess: ({ email, username }) => {
      setUser({ email, username })
      navigate("/")
    }
  })

  const { mutateAsync: resendEmail } = useMutation({
    mutationFn: async (emailOrUsername: string) => {
      const { error } = await client.api.auth["resent-email-confirmation"].post({ emailOrUsername })

      if (error) {
        throw new Error(error.value as string)
      }
    }
  })

  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    mode: "onBlur"
  })

  const onSubmit = ({ emailOrUsername, password }: FormValues) => {
    toast.promise(login({ emailOrUsername, password }), {
      loading: "Logging in...",
      success: "Logged in successfully",
      error: (error) => error.message === "Email not confirmed"
        ? (
          <>
            Email not confirmed.&ensp;
            <button
              type="button"
              onClick={() => toast.promise(resendEmail(emailOrUsername), {
                loading: "Resending email...",
                success: "Email confirmation resent",
                error: "Error resending email"
              })}
              className="text-cyan-500"
            >
              Resend
            </button>
          </>
        )
        : error.message
    })
  }

  return (
    <form
      className="p-8 rounded-lg shadow-md w-full md:w-1/2 lg:w-1/3 xl:w-1/4 bg-slate-800"
      onSubmit={handleSubmit(onSubmit)}
    >
      <h1 className="text-2xl font-semibold mb-4">Login</h1>
      <Input label="Email or Username" error={errors.emailOrUsername?.message} {...register("emailOrUsername")} />
      <Input label="Password" error={errors.password?.message} type="password" {...register("password")} />
      <Button type="submit">Login</Button>
      <p className="mt-4 text-center">
        Don't have an account? <a href="/auth/register" className="text-cyan-500">Register</a>
      </p>
      <p className="mt-4 text-center">
        <Link to="/auth/forgot-password" className="text-cyan-500">Forgot password?</Link>
      </p>
    </form>
  )
}

export default LoginPage

// frontend/src/routes/login/+page.svelte
<script lang="ts">
import { goto } from "$app/navigation"
import httpClient from "$lib/httpClient"
import { createMutation } from "@tanstack/svelte-query"
import { defaults, superForm } from "sveltekit-superforms"
import { zod, zodClient } from "sveltekit-superforms/adapters"
import { z } from "zod"
import Button from "../../components/Button.svelte"
import FormField from "../../components/FormField.svelte"

const schema = z.object({
	emailOrUsername: z.string().min(1, "Este campo é obrigatório"),
	password: z.string().min(1, "Este campo é obrigatório")
})

type FormData = z.infer<typeof schema>

const loginMutation = createMutation({
	mutationFn: async ({ emailOrUsername, password }: FormData) => {
		const { data, error } = await httpClient.auth.login.post({
			emailOrUsername,
			password
		})

		if (error) {
			if (error.status !== 422) {
				throw new Error(error.value.code, { cause: error.value })
			}

			throw new Error(error.value.message ?? "UNKNOWN_ERROR")
		}

		return data
	},
	onSuccess: () => {
		goto("/")
	},
	onError: (error, { emailOrUsername }) => {
		if (error.message === "EMAIL_NOT_VERIFIED") {
			const email = (error as { cause: { data: { email: string } } }).cause.data
				.email
			goto("/register/verify-email", { state: { email } })
		} else {
			// Handle other errors
			console.error("Login error:", error)
		}
	}
})

const form = superForm(defaults(zod(schema)), {
	SPA: true,
	validators: zodClient(schema),
	onUpdate: async ({ form }) => {
		if (form.valid) {
			await $loginMutation.mutateAsync(form.data)
		}
	}
})

const { enhance, delayed } = form
</script>

<div class="flex w-full min-h-screen items-center justify-center">
  <div class="card card-border card-lg bg-base-100 w-96 shadow-sm">
    <form class="card-body space-y-3" use:enhance>
      <h2 class="card-title">Entrar</h2>
      <FormField {form} field="emailOrUsername" label="Email" type="text" autocomplete="email" class="input-lg w-full" />
      <FormField {form} field="password" label="Senha" type="password" autocomplete="current-password" class="input-lg w-full" />
      <div class="card-actions">
        <Button type="submit" class="btn-lg btn-primary btn-block" loading={$delayed}>Entrar</Button>
        <div class="flex flex-col items-center w-full gap-3">
          <span class="text-base-content/50">Não tem uma conta? <a href="/register" class="link">Registrar</a></span>
          <span class="text-base-content/50 -mt-2"><a href="/forgot-password" class="link">Esqueceu a senha?</a></span>
        </div>
      </div>
    </form>
  </div>
</div>
