// src/routes/login/+page.svelte
<script lang="ts">
import { createForm } from "@tanstack/svelte-form"
import { createMutation } from "@tanstack/svelte-query"
import { z } from "zod"
import { goto } from "$app/navigation"
import { page } from "$app/state"
import httpClient from "$lib/httpClient"
import Button from "../../components/Button.svelte"
import FormField2 from "../../components/FormField.svelte"

const schema = z.object({
  emailOrUsername: z.string().min(1, "Este campo é obrigatório"),
  password: z.string().min(1, "Este campo é obrigatório")
})

type FormData = z.infer<typeof schema>

let errorMessage: string | null = $state(null)

const loginMutation = createMutation({
  mutationFn: async ({ emailOrUsername, password }: FormData) => {
    const { data, error } = await httpClient.auth.login.post({
      emailOrUsername,
      password
    })

    if (error) {
      if (error.status !== 422) {
        throw new Error(error.value.code, { cause: error.value })
      }

      throw new Error(error.value.message ?? "UNKNOWN_ERROR")
    }

    return data
  },
  onSuccess: () => {
    const redirectTo = page.url.searchParams.get("redirect")

    if (redirectTo && !redirectTo.startsWith("/")) {
      goto("/")
    }

    goto(redirectTo || "/")
  },
  onError: (error) => {
    if (error.message === "EMAIL_NOT_VERIFIED") {
      const email = (error as { cause: { data: { email: string } } }).cause.data
        .email
      goto("/register/verify-email", { state: { email } })
    } else {
      errorMessage = error.message
    }
  }
})

const form = createForm(() => ({
  defaultValues: {
    emailOrUsername: "",
    password: ""
  },
  onSubmit: async ({ value }) => {
    await $loginMutation.mutateAsync(value)
  }
}))
</script>

<div class="flex flex-col gap-8 w-full min-h-screen items-center justify-center">
  {#if errorMessage}
    <div role="alert" class="alert alert-error">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span>{errorMessage}</span>
    </div>
  {/if}
  <div class="card card-border bg-base-200 w-96 shadow-lg">
    <form
      class="card-body space-y-3"
      novalidate
      onsubmit={(e) => {
        e.preventDefault()
        e.stopPropagation()
        form.handleSubmit()
      }}
    >
      <h2 class="card-title">Entrar</h2>

      <form.Field name="emailOrUsername" validators={{ onBlur: schema.shape.emailOrUsername }}>
        {#snippet children(field)}
          <FormField2 field={field} label="Email" type="text" autocomplete="email" class="w-full" />
        {/snippet}
      </form.Field>

      <form.Field name="password" validators={{ onBlur: schema.shape.password }}>
        {#snippet children(field)}
          <FormField2 field={field} label="Senha" type="password" autocomplete="current-password" class="w-full" />
        {/snippet}
      </form.Field>

      <div class="card-actions">
        <Button type="submit" class="btn btn-primary btn-block" loading={$loginMutation.isPending}>Entrar</Button>
        <div class="flex flex-col items-center w-full gap-3">
          <span class="text-base-content">Não tem uma conta? <a href="/register" class="link">Registrar</a></span>
          <span class="text-base-content -mt-2"><a href="/forgot-password" class="link">Esqueceu a senha?</a></span>
        </div>
      </div>
    </form>
  </div>
</div>

// apps/web/src/pages/auth/login.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { toast } from "react-hot-toast";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { z } from "zod";
import Button from "../../components/Button";
import Input from "../../components/Input";
import logo from "../../images/logo.svg";
import client from "../../utils/httpClient";
import useStore from "../../utils/store";

const schema = z.object({
  email: z.string().min(1, "Required field"),
  password: z.string().min(1, "Required field"),
});
type FormValues = z.infer<typeof schema>;

const LoginPage: React.FC = () => {
  const setUser = useStore((state) => state.setUser);
  const navigate = useNavigate();

  const [params] = useSearchParams();
  const redirect = params.get("redirect") || "/";

  const {
    register,
    handleSubmit,
    formState: { errors, isValid },
    watch,
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    mode: "onBlur",
  });

  const onSubmit = ({ email, password }: FormValues) => {
    login({ email, password });
  };

  const email = watch("email");

  const { mutate: login, isPending } = useMutation({
    mutationFn: async ({ email, password }: FormValues) => {
      const { error, data } = await client.api.auth.login.post({
        email,
        password,
      });

      if (error) {
        throw new Error(error.value as string);
      }

      return data;
    },
    onSuccess: ({ email, firstName, lastName, id }) => {
      setUser({ email, firstName, lastName, id });
      navigate(redirect);
    },
    onError: (error) => {
      if (error.message === "Email not confirmed") {
        navigate("/auth/confirm-email", { state: { email } });
      }

      toast.error(error.message);
    },
  });

  return (
    <section className="bg-gray-50 dark:bg-gray-900">
      <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <a
          href="https://codelabs.vitordaniel.com"
          className="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white"
        >
          <img className="w-8 h-8 mr-2" src={logo} alt="logo" />
          Codelabs
        </a>
        <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
          <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
              Sign in to your account
            </h1>
            <form
              className="space-y-4 md:space-y-6"
              onSubmit={handleSubmit(onSubmit)}
            >
              <Input
                label="Email"
                error={errors.email?.message}
                {...register("email")}
              />
              <Input
                label="Password"
                error={errors.password?.message}
                type="password"
                {...register("password")}
              />
              <div className="flex items-center justify-between">
                <div className="flex items-start">
                  <div className="flex items-center h-5">
                    <input
                      id="remember"
                      aria-describedby="remember"
                      type="checkbox"
                      className="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800"
                      required
                    />
                  </div>
                  <div className="ml-3 text-sm">
                    <label
                      htmlFor="remember"
                      className="text-gray-500 dark:text-gray-300"
                    >
                      Remember me
                    </label>
                  </div>
                </div>
                <Link
                  to="/auth/forgot-password"
                  className="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500"
                >
                  Forgot password?
                </Link>
              </div>
              <Button
                type="submit"
                disabled={!isValid}
                loading={isPending}
                className="w-full"
              >
                Sign in
              </Button>
              <p className="text-sm font-light text-gray-500 dark:text-gray-400">
                Don’t have an account yet?{" "}
                <Link
                  to="/auth/register"
                  className="font-medium text-primary-600 hover:underline dark:text-primary-500"
                >
                  Sign up
                </Link>
              </p>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LoginPage;
